### ISSUE TITLE
add package to larrayenv to visualize h5 files

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#639]
@jehanneman asked for a tool to visualize h5 files.

@gdementen Why about `vitables`?

**Comment by gdementen** [comment]
I wouldn't do this because 1) AFAIR vitables 3.0 does not support the default format written by pandas (even if it displays them, the labels are in separate arrays, so it's pretty much useless) -- vitables master might support this though (it contains some code to support it but I don't know whether it works or not). 2) I intent to make larray-editor able to visualize .h5 files by itself "soon" (in a few months). All in all, I would just install vitables on his computer rather than add it to larrayenv.

**Comment by alixdamman** [comment]
Conclusion: users should use the viewer.

**Comment by alixdamman** [comment]
@gdementen Do I close this issue?
