### ISSUE TITLE
Add update method to Session and deprecate add

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#754]

**Comment by alixdamman** [comment]
@gdementen Are you OK with this issue?

The Session class already has methods like ``values``, ``keys`` and ``items`` and works like a custom dict with additional IO methods. So, in the same spirit, I would like to replace ``add`` by ``update``.

**Comment by gdementen** [comment]
adding .update would not hurt in any case and the current .add for axis object is mostly unused so it can go. However I am unsure, we will not resurrect .add someday if we ever introduce .name for arrays (so that arrays "know" the name of the variable they are stored into). This is very hypothetical though, so yes, it can go.
